---
# handlers file for installing_Docker
#
- name: docker_handler
  service:
    name: docker
    state: restarted
      
- name: Add user to docker group
  command: sudo usermod -aG docker precious

- name: Reboot server
  reboot:
